name: flutter_ebook_app
description: A Flutter EBook App UI With Audio Player

# Specify the environment SDK version constraint
environment:
  sdk: ">=2.18.0 <3.0.0"  # For Dart SDK versions

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/menu.JPEG
