name: firstapp
description: A Flutter app with EBook UI and Audio Player

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/facebook.JPEG
